name: Auto Merge and Restart

on:
  workflow_run:
    workflows: ["Bot Check Dev"]
    types:
      - completed

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fusionar Dev a Main
        run: |
          git checkout main
          git fetch origin main
          git merge --ff-only origin/main
          git merge origin/dev
          git push origin main

      # nueva linea
      - name: Forzar sincronización del servidor con Git
        run: |
          curl -X POST "https://panel.orionhost.xyz/api/client/servers/${{ secrets.SERVER_ID }}/command" \
          -H "Authorization: Bearer ${{ secrets.PTERO_API_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Accept: Application/vnd.pterodactyl.v1+json" \
          -d '{"command": "cd /home/container && git fetch --all && git reset --hard origin/main && git clean -fd"}'

      - name: Reiniciar Servidor en Pterodactyl
        run: |
          curl -X POST "https://panel.orionhost.xyz/api/client/servers/${{ secrets.SERVER_ID }}/power" \
          -H "Authorization: Bearer ${{ secrets.PTERO_API_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Accept: Application/vnd.pterodactyl.v1+json" \
          -d '{"signal": "restart"}'