name: Auto Merge and Restart

on:
  workflow_run:
    workflows: ["Bot Check Dev"]
    types:
      - completed

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest
    # Solo se ejecuta si el test de la rama dev fue exitoso
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fusionar Dev a Main
        run: |
          git checkout main
          git merge origin/dev
          git push origin main

      - name: Sync archivos al servidor (Limpieza de Cogs viejos)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: panel.orionhost.xyz
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.PTERO_API_KEY }}
          port: 2022
          protocol: sftp
          # 'dangerous-clean-slate' borra del servidor lo que NO esté en tu GitHub
          dangerous-clean-slate: true 
          # EXCLUIR archivos para que no se borren ni se sobrescriban en el servidor
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            analisis.db
            data.json
            .env
            *.log

      - name: Reiniciar Servidor en Pterodactyl
        run: |
          curl -X POST "https://panel.orionhost.xyz/api/client/servers/${{ secrets.SERVER_ID }}/power" \
          -H "Authorization: Bearer ${{ secrets.PTERO_API_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Accept: Application/vnd.pterodactyl.v1+json" \
          -d '{"signal": "restart"}'